-- Migration 11: Device pairing tables for kid-side companion flow.
--
-- NOTE: This file is a reconstruction of the ORIGINAL migration 11,
-- which was lost when the parent app directory was deleted on
-- 2026-07-11 (see claim-pairing/index.ts comment). The file below
-- was reconstructed on 2026-07-19 by inspecting the LIVE database
-- schema at wxjtksxugsirpowptpmz and cross-checking every column
-- against:
--   - lib/services/kid_device_service.dart
--   - supabase/functions/claim-pairing/index.ts
--   - supabase/functions/heartbeat/index.ts
--   - supabase/migrations/migration_12_add_role.sql
--   - supabase/migrations/migration_13_kid_device_revoke_policy.sql
--   - supabase/migrations/migration_14_kid_device_audit_log.sql
--
-- The tables, indexes, RLS policies, and the kid_devices_with_child
-- view ALREADY EXIST on the live database. This file is provided
-- for repo completeness and disaster recovery — do NOT apply it
-- to a database that already has these objects (use IF NOT EXISTS
-- / DROP IF EXISTS to be safe).
--
-- Verified end-to-end on 2026-07-19: generatePairingCode() →
-- claim-pairing POST → kid_devices row + parents role='kid' row
-- created → parent can see device via kid_devices_with_child view.

-- ===========================================================================
-- device_pairings
-- ===========================================================================
-- Stores 6-digit pairing codes generated by the parent app.
-- The PRIMARY KEY is `code` (text), not a UUID — the code itself
-- is the natural key and is how the claim-pairing Edge Function
-- looks up rows.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS device_pairings (
  code            TEXT PRIMARY KEY,
  family_id       UUID NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  child_id        UUID NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  created_by      UUID NOT NULL REFERENCES auth.users(id),
  expires_at      TIMESTAMPTZ NOT NULL,
  claimed_at      TIMESTAMPTZ,
  claimed_by_device UUID REFERENCES kid_devices(id)
);

CREATE INDEX IF NOT EXISTS device_pairings_code_idx
  ON device_pairings (code);

CREATE INDEX IF NOT EXISTS device_pairings_family_id_idx
  ON device_pairings (family_id);

CREATE INDEX IF NOT EXISTS device_pairings_expires_at_idx
  ON device_pairings (expires_at);

ALTER TABLE device_pairings ENABLE ROW LEVEL SECURITY;

-- Original fine-grained policies from migration 11:
DROP POLICY IF EXISTS "Parents can create pairing codes" ON device_pairings;
CREATE POLICY "Parents can create pairing codes"
  ON device_pairings FOR INSERT
  TO authenticated
  WITH CHECK (
    created_by = auth.uid()
    AND EXISTS (
      SELECT 1 FROM parents p
      WHERE p.family_id = device_pairings.family_id
      AND p.id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Parents can see their pairing codes" ON device_pairings;
CREATE POLICY "Parents can see their pairing codes"
  ON device_pairings FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM parents p
      WHERE p.family_id = device_pairings.family_id
      AND p.id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Parents can delete their pairing codes" ON device_pairings;
CREATE POLICY "Parents can delete their pairing codes"
  ON device_pairings FOR DELETE
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM parents p
      WHERE p.family_id = device_pairings.family_id
      AND p.id = auth.uid()
    )
  );

-- Service-role access (Edge Functions use service_role for writes):
DROP POLICY IF EXISTS "Service role manages device_pairings writes" ON device_pairings;
CREATE POLICY "Service role manages device_pairings writes"
  ON device_pairings FOR ALL
  TO public
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ===========================================================================
-- kid_devices
-- ===========================================================================
-- One row per physical device paired to a kid. Created by the
-- claim-pairing Edge Function (service_role). Parents can read
-- and update (revoke) but not insert — inserts only via Edge Fn.
-- ===========================================================================

CREATE TABLE IF NOT EXISTS kid_devices (
  id          UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  child_id    UUID NOT NULL REFERENCES children(id) ON DELETE CASCADE,
  family_id   UUID NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  device_name TEXT,
  paired_at   TIMESTAMPTZ DEFAULT now(),
  last_seen_at TIMESTAMPTZ,
  revoked_at  TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS kid_devices_family_id_idx
  ON kid_devices (family_id);

CREATE INDEX IF NOT EXISTS kid_devices_child_id_idx
  ON kid_devices (child_id);

ALTER TABLE kid_devices ENABLE ROW LEVEL SECURITY;

-- Original policies from migration 11:
DROP POLICY IF EXISTS "Parents can read family kid devices" ON kid_devices;
CREATE POLICY "Parents can read family kid devices"
  ON kid_devices FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM parents p
      WHERE p.family_id = kid_devices.family_id
      AND p.id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Parents can see family kid devices" ON kid_devices;
CREATE POLICY "Parents can see family kid devices"
  ON kid_devices FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM parents p
      WHERE p.family_id = kid_devices.family_id
      AND p.id = auth.uid()
    )
  );

-- Service-role access (Edge Functions create/revoke devices):
DROP POLICY IF EXISTS "Service role manages kid_devices writes" ON kid_devices;
CREATE POLICY "Service role manages kid_devices writes"
  ON kid_devices FOR ALL
  TO public
  USING (auth.role() = 'service_role')
  WITH CHECK (auth.role() = 'service_role');

-- ===========================================================================
-- kid_devices_with_child view
-- ===========================================================================
-- Joins kid_devices with children so the parent app can show
-- "Aarav's Pixel 8" without N+1 queries. Status is derived from
-- last_seen_at and revoked_at. Defined here for completeness but
-- also referenced / re-CREATEd in migration_13.
-- ===========================================================================

DROP VIEW IF EXISTS kid_devices_with_child;
CREATE VIEW kid_devices_with_child AS
  SELECT
    kd.id,
    kd.family_id,
    kd.child_id,
    c.name AS child_display_name,
    kd.device_name,
    kd.paired_at,
    kd.last_seen_at,
    kd.revoked_at,
    CASE
      WHEN kd.revoked_at IS NOT NULL THEN 'revoked'
      WHEN kd.last_seen_at IS NULL THEN 'unknown'
      WHEN kd.last_seen_at > now() - interval '90 seconds' THEN 'online'
      WHEN kd.last_seen_at > now() - interval '24 hours' THEN 'recent'
      ELSE 'stale'
    END AS status
  FROM kid_devices kd
  LEFT JOIN children c ON c.id = kd.child_id;
